### ISSUE TITLE
Expand display-logic to include these features:

### ISSUE THREAD

**Issue by Josua2012** [unclecheese/silverstripe-display-logic#1]
Hi Aaron!

Could you expand display-logic to include these features?

$products->AssignValue("XXXX")->If("Order")->isChanged();
$products->AssignFieldValue("FieldName")->If("FieldName")->isChanged();
$products->AssignExpression('FieldName1+"22"+FieldName2')->If("FieldName")->isChanged();
// Sum of all fields starting with 'FieldName' if any of these fields is modified
$products->AssignSum('FieldName_')->If("FieldName_")->isChanged();
$products->ErrorIf("The product code is greater than 20.")->isGreaterThan(20);

Thanks for this great module.
Regards,
Jose A.

**Comment by michalkleiner** [comment]
Hello! Thank you for raising the feature request, we appreciate you taking the time.

If you can provide a PR, we will consider it. However, as already mentioned above, some of the suggested features are a bit out of scope for the module.

For now, I'll close the issue since it's outdated and we're now on Silverstripe CMS 4.12.0 and Display Logic 2.0.5
