### ISSUE TITLE
1.5.1 and 1.6.0 missing commits

### ISSUE THREAD

**Issue by thats4shaw** [unclecheese/silverstripe-display-logic#101]
Hi @unclecheese - just noticed that the 1.5.1 and 1.6.0 tags is missing a bunch of commits from 2016 and 2017.

Hopefully an easy one to sort 👍.

**Comment by marc-firebrand** [comment]
Hi @unclecheese ,

Issue is also impacting 1.4.4, missing around 30 commits and is locked to 3.1.* (instead of being ^3.2)
The module is currently not working in 3.7.1 because of the outdated display_logic.js
FYI 1.5.0 is working in 3.6.6 if thats any help

Thanks for your help 👍

**Comment by kinglozzer** [comment]
Thank god, I thought I was going insane 🤣

**Comment by bummzack** [comment]
AFAIK all the changes are ready in this PR: https://github.com/unclecheese/silverstripe-display-logic/pull/98

**Comment by unclecheese** [comment]
Alright, have merged. Thanks for your help, everyone. What a mess. Have tagged a new release `1.7` because I can't in my mind justify how a merge like that could be a patch release. :)

**Comment by bummzack** [comment]
Why shouldn't it be a patch release? The last stable was `1.5`, then the PHP 7.2 Support was based on an outdated branch, that reverted back to a state prior to `1.5`. This was then released as `1.5.1` and `1.6`. So what happened is that `1.5.1` and `1.6` were actually really breaking changes, because a _lot_ of work was reverted.

Happy that this has been resolved now, but I urge you to also create a new branch for the `1.x` release line. So that this doesn't happen again.

**Comment by unclecheese** [comment]
Yeah, you're right. The root of this fiasco can be traced back to the poorly named SS 3.x branch. This module predates my understanding of semver (and SS's implementation thereof).

Which leads me to your first question -- the version numbers have always been arbitrary, and based on the release history, this just felt like a bit enough change set (albeit existing code) that 1.7 felt like the best option in context.

In the spirit of moving more toward semver, a `1` branch has been created, and `1.2` deleted.
