### ISSUE TITLE
TreeDropdownField isn't shown or hidden

### ISSUE THREAD

**Issue by Firesphere** [unclecheese/silverstripe-display-logic#38]
Display Logic doesn't work with TreeDropdownFields.

**Comment by unclecheese** [comment]
"Doesn't work?"

**Comment by Firesphere** [comment]
Sorry for the very short issue. I did not have time to make a real issue on the spot.

The problem is, TreeDropdownfield does not have the callback for  		$this->extend('onBeforeRender', $this);
in it's Field() call. And besides that, does also not render the callbacks in its template.

**Comment by unclecheese** [comment]
If you have other fields that depend on the value of your TreeDropdownField, it's not going to work, I don't think, because TreeDropdownField doesn't fire change events -- at least not in a way that's being accounted for.

If the issue is just getting the TreeDropdownField's display to depend on the values of other fields, you probably just want to wrap it in `DisplayLogicWrapper`, like you would GridField or UploadField.

**Comment by Firesphere** [comment]
Ahhh, I overlooked the DisplayLogicWrapper. Nevermind, issue resolved itself ;)
