### ISSUE TITLE
Doesn't it work with TabSet and HeaderField?

### ISSUE THREAD

**Issue by sommereder** [unclecheese/silverstripe-display-logic#45]
HeaderField ignores it in total, and TabSet only vanishes and never appears again. Also tried both fields with the wrapper, but also doesn't work. Have a regular TextField as a control instance and that works perfectly.

Using SilverStripe v3.2.1 and DisplayLogic v1.3.1. Thanks.

**Comment by michalkleiner** [comment]
Hello! Thank you for raising the issue and apologies it hasn't been responded to earlier.

I'll close this issue since it's outdated and we're now on Silverstripe CMS 4.12.0 and Display Logic 2.0.5.

If your problem persists feel free to open a new bug report and provide replication steps and information on what version of Silverstripe CMS and the module you're using. Thank you for your understanding.
