### ISSUE TITLE
Not working with Bootstrap Front-end forms

### ISSUE THREAD

**Issue by craig-opticblaze** [unclecheese/silverstripe-display-logic#72]
I know there are issues posted for this already but I am using silverstripe bootstrap forms and I cannot get display-logic working with them. It will work in the CMS no problem though. 

I have included the DisplayLogicWrapper and while it wraps the field correctly and hides it, once I apply logic it doesn't show. 

Is there a possible way around this?

Edit: Found out that using Display-Logic 1.0.8 works with Bootstrap forms. Any version higher will not work,

**Comment by michalkleiner** [comment]
Hello! Thank you for raising the issue and apologies it hasn't been responded to earlier.

I'll close this issue since it's outdated now, but if your problem persists feel free to open a new bug report and provide replication steps and information on what version of Silverstripe CMS and the module you're using.
